### ISSUE TITLE
Error Parsing IPv6 During Swarm Cluster Join

### ISSUE THREAD

**Issue by jtopjian** [docker/libnetwork#1601] opened 2016-12-23 20:09 UTC
When creating a Swarm cluster with IPv6 addresses, a worker will fail to fully join the cluster due to the brackets being stripped. The resulting error is:

```
time="2016-12-23T07:27:26.368614166Z" level=warning msg="2016/12/23 07:27:26 
[WARN] memberlist: Failed to resolve 2001:fd00:4:1000:f816:3eff:fe78:3323: 
too many colons in address 2001:fd00:4:1000:f816:3eff:fe78:3323\n"
```

This is happening during the [net.SplitHostPort](https://golang.org/pkg/net/#SplitHostPort) call [here](https://github.com/docker/libnetwork/blob/c5861834b0177a51ddc9879df521a0826fd8eec4/agent.go#L190). 

A quick patch of:

```go
remoteIP := net.ParseIP(remoteAddr)
if remoteIP.To4() == nil {
        remoteAddr = fmt.Sprintf("[%s]", remoteIP)
}
```

resolves the issue and the worker is then able to successfully join the cluster, though I'm not sure if that's the best way to resolve the issue?

**Comment by mbsimonovic** [comment] 2017-08-08 10:38
i'm getting these with docker 17.06.0-ce (build 02c1d87) despite successful join!? 

```
level=warning msg="memberlist: Failed to resolve 2a01:xxx1 
too many colons in address 2a01:xxx1 \n"
level=warning msg="memberlist: Failed to resolve 2a01:xxx1 
too many colons in address 2a01:xxx2 \n"
level=error msg="Failed to join memberlist [2a01:xxx1 2a01:xxx2] on retry: 2 error(s) occurred
```

it's a 3 node cluster with 2 managers, and two other nodes (one manager one worker) report this issue, the ones that had to join.

**Comment by skrivy** [comment] 2018-02-22 12:01
Same here

```
root@compute2:~# docker version
Client:
 Version:       17.12.0-ce
 API version:   1.35
 Go version:    go1.9.2
 Git commit:    c97c6d6
 Built: Wed Dec 27 20:11:19 2017
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.0-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.2
  Git commit:   c97c6d6
  Built:        Wed Dec 27 20:09:54 2017
  OS/Arch:      linux/amd64
  Experimental: false
```

**Comment by fcrisciani** [comment] 2018-02-22 16:07
On 18.02 looks fixed, I guess we may have missed some backport. I will take a look

**Comment by skrivy** [comment] 2018-02-22 17:35
Just tested docker-ce from edge repository.

```
root@compute2:~# docker version
Client:
 Version:       18.02.0-ce
 API version:   1.36
 Go version:    go1.9.3
 Git commit:    fc4de44
 Built: Wed Feb  7 21:16:25 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm

Server:
 Engine:
  Version:      18.02.0-ce
  API version:  1.36 (minimum version 1.12)
  Go version:   go1.9.3
  Git commit:   fc4de44
  Built:        Wed Feb  7 21:14:59 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

```
Feb 22 18:34:28 compute2 dockerd[563]: time="2018-02-22T18:34:28.960213941+01:00" level=warning msg="memberlist: Failed to resolve XXXXXXXX: address XXXXXXXX:7946: too many colons in address"
Feb 22 18:34:28 compute2 dockerd[563]: time="2018-02-22T18:34:28.961166382+01:00" level=error msg="Failed to join memberlist [XXXXXXXX] on retry: 1 error(s) occurred:\n\n* Failed to resolve XXXXXXXX: address XXXXXXXX:7946: too many colons in address"
```

**Comment by fcrisciani** [comment] 2018-02-22 17:40
@skrivy the issue is in memberlist (https://github.com/hashicorp/memberlist/pull/69), I was using a self build image, I will check the vendoring in moby to make sure that is in line and contains that fix. If you build moby master that should be fixed

**Comment by fcrisciani** [comment] 2018-02-22 17:43
Yep looks like 18.02 is still vendoring the old memberlist: `github.com/hashicorp/memberlist v0.1.0` so does not contains the IPv6 fix. sorry for the confusion

**Comment by fcrisciani** [comment] 2018-02-22 17:45
18.03 that is coming out soon, has the correct version

**Comment by fcrisciani** [comment] 2018-02-22 17:58
@thaJeztah should we consider to bump the memberlist version on 17.12 also at this point?

In the mean time closing this one now that the mystery is solved

**Closed by fcrisciani** 2018-02-22 17:58 UTC

**Comment by skrivy** [comment] 2018-02-22 20:17
I can confirm that this works with the latest version from the test repository.

**Comment by thaJeztah** [comment] 2018-02-23 15:08
@fcrisciani would that be just revendoring member list, or also the other changes? https://github.com/docker/libnetwork/pull/2040 ?

**Comment by fcrisciani** [comment] 2018-02-23 16:07
@thaJeztah for this specific is only revendoring
