### ISSUE TITLE
Support VXLAN on Kernels <= 3.15

### ISSUE THREAD

**Issue by jgkamat** [docker/libnetwork#329] opened 2015-06-24 14:39 UTC
This is a continuation from [the issue I posted in docker/docker](https://github.com/docker/docker/issues/14145), see there for more details.

As of now, the overlay driver is working fine on kernels 3.16 and up.

**Comment by dave-tucker** [comment] 2015-07-14 17:10
Thanks for the report @jgkamat, we'll try and get this one fixed in time for the next release!

**Comment by jgkamat** [comment] 2015-07-14 17:43
Thanks @dave-tucker! :smile:

**Comment by mavenugo** [comment] 2015-07-16 05:23
@mrjana the error seen in kernels < 3.15 suggests that we arent able to set the vxlan interface in the newly created namespace for the overlay network.
As a workaround, shall we not create a namespace for each network in overlay driver for kernels < 3.15 ?

I understand that this changes the design. But do you have any other suggestion for the sake of backward compatibility ?

**Comment by dave-tucker** [comment] 2015-07-16 13:01
@mavenugo not a bad hypothesis, although I'm able to create a vxlan interface in a netns on 14.04
```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo ip netns exec dave ip link add vxlan0 type vxlan id 42 group 239.1.1.1 dev lo
vagrant@vagrant-ubuntu-trusty-64:~$ sudo ip netns exec dave ip a
1: lo: <LOOPBACK> mtu 65536 qdisc noop state DOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: vxlan0: <BROADCAST,MULTICAST> mtu 65486 qdisc noop state DOWN group default
    link/ether 6a:92:c7:24:af:f5 brd ff:ff:ff:ff:ff:ff
vagrant@vagrant-ubuntu-trusty-64:~$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-55-generic #92-Ubuntu SMP Sun Jun 14 18:32:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
vagrant@vagrant-ubuntu-trusty-64:~$
```

**Comment by dave-tucker** [comment] 2015-07-16 13:02
... and just tested on a machine which exhibits this issue with the multihost driver...

```
root@multihost1:~# ip netns exec cf0e4b5f38d6 ip link add vxlan1 type vxlan id 1 learning proxy l2miss l3miss
root@multihost1:~# ip netns exec cf0e4b5f38d6 ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether ce:10:de:70:99:57 brd ff:ff:ff:ff:ff:ff
    inet 172.21.255.254/16 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::cc10:deff:fe70:9957/64 scope link
       valid_lft forever preferred_lft forever
3: vxlan1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default
    link/ether 46:cd:67:92:49:c8 brd ff:ff:ff:ff:ff:ff
root@multihost1:~#
```

**Comment by dave-tucker** [comment] 2015-07-16 13:29
Ok, and now I have a root cause :)

Turns out, prior to https://github.com/torvalds/linux/commit/f01ec1c017dead42092997a2b8684fcab4cbf126, VXLAN interfaces were created  with the `NETIF_F_NETNS_LOCAL` flag preventing them from being moved to a network namespace.

Even though you can create a VXLAN interface in a netns, I'm not sure it would work prior to this patch as the receiving (or global) netns won't know to where to send any encapsulated frames it receives.

 - If we want to continue to use VXLAN only, we'll have to have interface in the global netns per network
- We *could* provide a fallback for VXLAN+VLAN encapsulation for <=3.15
  - 1 VXLAN interface and VXLAN bridge in global netns
  -  VLAN tagged veth pair to bridge in the network netns

**Comment by mavenugo** [comment] 2015-07-17 20:18
@dave-tucker Yes. And hence my previous comment -

>> @mrjana the error seen in kernels < 3.15 suggests that we arent able to set the vxlan interface in the newly created namespace for the overlay network. As a workaround, shall we not create a namespace for each network in overlay driver for kernels < 3.15 ?

Do you agree ?

@mrjana WDYT ?
We are able to create the vxlan interface in the netns, but its the set that fails. If I understand our original discussion, we were relying on the fact that by creating the vxlan interface on the global ns and moving it to the network-specific ns actually helps in resolving the ns that the traffic is destined to. 
am not too sure if creating vxlan interface inside of the netns behave any differently ?

**Comment by rhim** [comment] 2015-09-09 23:52
So for recent enterprise linux distros that are running somewhat older kernels (e.g., centos 7 with kernel 3.10), what's the plan to have overlay driver working there. Any proposals?

**Comment by rhim** [comment] 2015-10-01 19:53
@mavenugo : Could you speculate "how much" effort it would to make overlay driver work on kernels <=3.15? Is it possible to achieve this with only overlay driver changes, or it must include a change to the kernel? If latter, then I believe it's no different than using the new kernel - so ppl must move on to them.

Would it be possible to make overlay driver work with older kernel but with other drivers and utilities, like socketplane used to with openvswitch? Or it isn't really worth it.

**Comment by mavenugo** [comment] 2015-12-18 16:48
@jgkamat @rhim PTAL #821 . We now support kernels < 3.16. Should be made available in next Docker release.

**Comment by jgkamat** [comment] 2015-12-18 20:45
nice, thanks for all your hard work! :smile:

**Comment by rhim** [comment] 2015-12-18 20:57
This is awesome! Made my day :-).

On Fri, Dec 18, 2015 at 12:45 PM, Jay Kamat <notifications@github.com>
wrote:

> nice, thanks for all your hard work! [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/libnetwork/issues/329#issuecomment-165894142>.
>



-- 
-Himanshu

**Closed** 2015-12-18 22:09 UTC
Labels: bug

**Comment by tnithya** [comment] 2015-12-19 02:01
Much needed update. 
Thanks to Docker team for seeing this through. 

Nithya

**Comment by alvinr** [comment] 2015-12-19 02:36
Nice one Networking team!
