### ISSUE TITLE
network veth interface leak in docker

### ISSUE THREAD

**Issue by moypray** [docker/libnetwork#1850] opened 2017-07-24 10:53 UTC
Hi all,
 When I run docker test in my local environment, the docker daemon would be killed while testing process, But after all the test stopped and stopped all the containers, I found that there are some network interfaces existing on host. 

So I supposed there is network interface leak in docker. BTW, I use the bridge mode in docker.

After checking the libnetwork code, I found that if we killed docker after libnetwrok has created endpoint before saving it in blob, and the leak will be existing.

If we add `time.Sleep(10*time.Second)` before saving it to blob, after creating endpiont, it will be reproduced.  e.g.  add here: https://github.com/docker/libnetwork/blob/master/network.go#L1135

I have checked the libnetwork cleanup sandbox/network/endpoint mechanism. I think if we save the interface data into blob done, It won't leak at all.

So I wonder if we could update store first, and then create the endpoint ? Or any other good solution about this?

Thanks!

**Comment by moypray** [comment] 2017-07-27 11:46
Reproduce steps:
1. call `netowrk.CreateEndpoint`
2. create Endpoint using bridge driver on host.
3. `kill docker`
4. should update store, but docker was killed.

===> after docker restart. will sync and remove the stopped container endpoints, but the veth pair was not saved in db. libnetwork could not remove it. the device will leak on host.

Actually, In my environment, we run docker for long time for testing (maybe docker crashed or killed at that time). Then I cleanup the environment I found the leak.


I have submit a patch. To save endpoint first, then create the interfaces. But I am not familiar with libnetwork, and do not know if it is a good way. 
Is this solution ok for libnetwork?  Or is there any other ideas to fix this?

**Comment by selansen** [comment] 2017-11-17 22:48
I  see different behavior when I  kill dockerd with two different way ( Ctrl C  and "kill -9 dockerd")

when I tried with Ctrl C, I see below output and veths are getting cleaned up properly.
DEBU[2017-11-17T22:35:12.179551174Z] daemon configured with a 15 seconds minimum shutdown timeout 
DEBU[2017-11-17T22:35:12.179565223Z] start clean shutdown of all containers with a 15 seconds timeout... 
DEBU[2017-11-17T22:35:12.179583726Z] stopping e48bf83d2f75b03441646a57df8413ff436b6737d860ba9c82835785eefc8f0f 
DEBU[2017-11-17T22:35:12.179607669Z] Sending kill signal 15 to container e48bf83d2f75b03441646a57df8413ff436b6737d860ba9c82835785eefc8f0f 
DEBU[2017-11-17T22:35:12.179721392Z] stopping e3aadcd6ed86df17f17fc00131e66770d08890981feba68aff9bbf201caaef34 
DEBU[2017-11-17T22:35:12.179745774Z] Sending kill signal 15 to container e3aadcd6ed86df17f17fc00131e66770d08890981feba68aff9bbf201caaef34 
DEBU[2017-11-17T22:35:12.179799428Z] stopping 03a4756b999baeccd1015fd7113d2e60994725df221aaabc3e896f6402a9fa41 
DEBU[2017-11-17T22:35:12.179815334Z] Sending kill signal 15 to container 03a4756b999baeccd1015fd7113d2e60994725df221aaabc3e896f6402a9fa41 
DEBU[2017-11-17T22:35:12.179863821Z] stopping cafa5f23efc00ff6698d3ace198b2b632e262ccf2dc889aa00b4c96df492e5c8 
DEBU[2017-11-17T22:35:12.179879796Z] Sending kill signal 15 to container cafa5f23efc00ff6698d3ace198b2b632e262ccf2dc889aa00b4c96df492e5c8 
INFO[2017-11-17T22:35:22.212720832Z] Container 03a4756b999baeccd1015fd7113d2e60994725df221aaabc3e896f6402a9fa41 failed to exit within 10 seconds of signal 15 - using the force 
DEBU[2017-11-17T22:35:22.212763749Z] Sending kill signal 9 to container 03a4756b999baeccd1015fd7113d2e60994725df221aaabc3e896f6402a9fa41 
INFO[2017-11-17T22:35:22.226901451Z] Container e3aadcd6ed86df17f17fc00131e66770d08890981feba68aff9bbf201caaef34 failed to exit within 10 seconds of signal 15 - using the force 
DEBU[2017-11-17T22:35:22.227031710Z] Sending kill signal 9 to container e3aadcd6ed86df17f17fc00131e66770d08890981feba68aff9bbf201caaef34 
INFO[2017-11-17T22:35:22.227830661Z] Container e48bf83d2f75b03441646a57df8413ff436b6737d860ba9c82835785eefc8f0f failed to exit within 10 seconds of signal 15 - using the force 
DEBU[2017-11-17T22:35:22.227893245Z] Sending kill signal 9 to container e48bf83d2f75b03441646a57df8413ff436b6737d860ba9c82835785eefc8f0f 
INFO[2017-11-17T22:35:22.239082131Z] Container cafa5f23efc00ff6698d3ace198b2b632e262ccf2dc889aa00b4c96df492e5c8 failed to exit within 10 seconds of signal 15 - using the force 
DEBU[2017-11-17T22:35:22.239218178Z] Sending kill signal 9 to container cafa5f23efc00ff6698d3ace198b2b632e262ccf2dc889aa00b4c96df492e5c8 



But when I use "Kill -9 dockerd"
none of the veth interfaces are getting cleaned up when I run dockerd again.


I also introduced 20 seconds delay after creating end endpoint but before saving into store. In this case also behavior with Ctrl C and Kill command is different.

Could you pls confirm how did you kill dockerd while testing ?  by looking at the logs and code, I believe Ctrl C takes proper clean up code path way and veth  is not  getting cleaned up when it crashes before store (blob) happens. Pls provide your input.

**Comment by selansen** [comment] 2017-11-20 19:51
May I know which version are you using ? is it CE or EE ?
The reason I am asking is, when I kill dockerd with EE and My private image (pulled from moby/moby), I see two different behavior on host. with EE, I see containers are getting stopped and veth is getting removed .  But with my Private image , I  see containers are still running even after I kill dockerd and veth still present. I showed the behavior to TEC engineer Trapier and he was surprised to see the behavior . Pls let me know which version of docker  did you use ? 

In the mean time I will pull EE source and try to make changes and see if I can reproduce the issue. 

Earlier I was testing Docker-in-Docker setup but now now I am using Ubuntu VM as host .

**Comment by moypray** [comment] 2017-11-21 01:36
Hi @selansen  sorry for late reply.
I used `kill -9 <docker pid>`, the reproduce process is as below:
1.  add some sleep after creating the veth, and before storing it to db. (you have done it, good).
2.  `ip addr` to check the network devices on host, 
3. start docker, (you'd better add some logs, after creating veth, before storing it in db.)
4. `kill -9 dockerd`
5. `ip addr` to check to the veth,  they must be existing on host, docker does not have chance to delete them.
6. startup docker again. ( to check the veth again, if you do not see them, this means the veth has been saved in db, you should kill dockrd more earlier.  docker (or we can say libnetwork) will remove the veth which do not connected to container but record in db at startup).

**Comment by moypray** [comment] 2017-11-21 01:38
I was using 1.11.2 version of docker, but the logic of the libnetwork code is the same. ( not docker in docker.  Ubuntu VM should be OK)

**Comment by selansen** [comment] 2017-11-21 04:07
I Moved to EE latest version and I am able to reproduce the issue in Ubuntu host. 
I faced different issue with CE edition (containers were running even after I kill dockerd). I checked the docker inspect and made sure all the parameters are correct. 
Will continue to debug on EE version.

**Comment by moypray** [comment] 2017-11-21 06:47
I just tried 1.11.2 version, it is very old. but for this issue, I think, it is not relative with docker version.

not familiar with latest version of docker.

**Comment by selansen** [comment] 2017-11-21 17:21
Below is my testing and looks good to me.  can you pls confirm if I am testing it correctly?

Before killing dokcer D, VETH 373 & 374 got created for attaching network to a container 
====================================================================
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 12:da:01:fa:7d:1a brd ff:ff:ff:ff:ff:ff
    inet 172.31.51.94/20 brd 172.31.63.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::10da:1ff:fefa:7d1a/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d3:19:e8:b4 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d3ff:fe19:e8b4/64 scope link 
       valid_lft forever preferred_lft forever
8: docker_gwbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c2:c1:2e:09 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c2ff:fec1:2e09/64 scope link 
       valid_lft forever preferred_lft forever
333: veth372a389@vethce2a52c: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 6a:92:a9:2a:83:99 brd ff:ff:ff:ff:ff:ff
334: vethce2a52c@veth372a389: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue master br-48c75de92d13 state LOWERLAYERDOWN group default 
    link/ether d6:61:51:f2:d2:68 brd ff:ff:ff:ff:ff:ff
372: veth4f34f95@if371: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether b6:e2:8a:f3:59:03 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::b4e2:8aff:fef3:5903/64 scope link 
       valid_lft forever preferred_lft forever
373: vethb1b9eaf@veth4ac0e51: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether a2:88:a5:29:26:e0 brd ff:ff:ff:ff:ff:ff
374: veth4ac0e51@vethb1b9eaf: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue master br-48c75de92d13 state LOWERLAYERDOWN group default 
    link/ether 82:5f:78:75:6e:e8 brd ff:ff:ff:ff:ff:ff
170: br-dae4b713d51b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:5f:df:c3:97 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-dae4b713d51b
       valid_lft forever preferred_lft forever
    inet6 fe80::42:5fff:fedf:c397/64 scope link 
       valid_lft forever preferred_lft forever
250: br-48c75de92d13: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d7:ec:f6:2b brd ff:ff:ff:ff:ff:ff
    inet 172.55.0.1/16 scope global br-48c75de92d13
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d7ff:feec:f62b/64 scope link 
       valid_lft forever preferred_lft forever
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ 
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ 
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ 
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ sudo kill -9 14073
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ 
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ 
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-dev/binary-daemon$ 
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/bundles/17.06.0-

After dokcerD comes back VETH 373 & 374 got deleted
====================================================================dev/binary-daemon$ ip a 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9001 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 12:da:01:fa:7d:1a brd ff:ff:ff:ff:ff:ff
    inet 172.31.51.94/20 brd 172.31.63.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::10da:1ff:fefa:7d1a/64 scope link 
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d3:19:e8:b4 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d3ff:fe19:e8b4/64 scope link 
       valid_lft forever preferred_lft forever
8: docker_gwbridge: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c2:c1:2e:09 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 scope global docker_gwbridge
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c2ff:fec1:2e09/64 scope link 
       valid_lft forever preferred_lft forever
333: veth372a389@vethce2a52c: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 6a:92:a9:2a:83:99 brd ff:ff:ff:ff:ff:ff
334: vethce2a52c@veth372a389: <NO-CARRIER,BROADCAST,MULTICAST,UP,M-DOWN> mtu 1500 qdisc noqueue master br-48c75de92d13 state LOWERLAYERDOWN group default 
    link/ether d6:61:51:f2:d2:68 brd ff:ff:ff:ff:ff:ff
380: veth193ad10@if379: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker_gwbridge state UP group default 
    link/ether 4a:c8:13:f7:64:7f brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::48c8:13ff:fef7:647f/64 scope link 
       valid_lft forever preferred_lft forever
170: br-dae4b713d51b: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:5f:df:c3:97 brd ff:ff:ff:ff:ff:ff
    inet 172.19.0.1/16 scope global br-dae4b713d51b
       valid_lft forever preferred_lft forever
    inet6 fe80::42:5fff:fedf:c397/64 scope link 
       valid_lft forever preferred_lft forever
250: br-48c75de92d13: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default 
    link/ether 02:42:d7:ec:f6:2b brd ff:ff:ff:ff:ff:ff
    inet 172.55.0.1/16 scope global br-48c75de92d13
       valid_lft forever preferred_lft forever
    inet6 fe80::42:d7ff:feec:f62b/64 scope link 
       valid_lft forever preferred_lft forever
docker@ELANGO-TESTKIT-ubuntu-2:~/docker-ee/components/engine/

**Comment by fcrisciani** [comment] 2017-12-13 05:35
code merged, closed by https://github.com/docker/libnetwork/pull/2024

**Closed by fcrisciani** 2017-12-13 05:35 UTC
