### ISSUE TITLE
Docker reports "ipv4 pool is empty" - but it is not

### ISSUE THREAD

**Issue by rayjohnson** [docker/libnetwork#1942] opened 2017-09-18 21:49 UTC
I have a compose file with a networks section like this:

```
networks:
  front:
    ipam:
      driver: qnet
      options: 
        iface: eth1
  back:
    driver: customer-driver-1
    internal: true
    ipam:
      driver: default
```

When I do my docker-compose up - I get this:
```
Creating network "mywordpress_front" with the default driver
ERROR: ipv4 pool is empty
DESKTOP-8O0TNFC:mywordpress
```

However, I know there are plenty of IPs available.  Also, this works fine when I create the network via docker command line:
`docker network create -d qnet --ipam-driver=qnet --ipam-opt=iface=eth1 qnet-dhcp-eth1
`
I'm fairly certain I have the compose syntax correct.  Why am I getting this error and what does it mean?

ray

**Comment by thaJeztah** [comment] 2017-09-18 22:00
The IPAM options are currently not supported in the v3 format, only in v2.x; https://github.com/docker/docker.github.io/issues/1528 is your compose file using the v2 or v3 version?

**Comment by rayjohnson** [comment] 2017-09-18 22:16
I do have then as v2 format.

**Comment by thaJeztah** [comment] 2017-09-18 22:24
It may be worth putting your daemon in debug mode, and debug the API calls that are made (when enabling debug mode, API calls are output in the daemon logs); given that manually creating a network with these options works, but doing so through docker-compose doesn't, I suspect docker-compose doesn't make the correct API calls to create the network.

The easiest way to put the daemon in debug mode is using a `daemon.json` configuration file (see the `dockerd` reference; https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file). If you don't have a daemon configuration file, create the file at `/etc/docker/daemon.json` containing:

```json
{"debug":true}
```

Then reload the daemon (`sudo systemctl reload docker.service`)

**Comment by fcrisciani** [comment] 2018-01-29 21:39
@rayjohnson any update on this? can you try to reproduce on 17.12?

**Comment by fcrisciani** [comment] 2018-02-23 23:40
closing this, let us know if the problem is not fixed

**Closed by fcrisciani** 2018-02-23 23:40 UTC
