### ISSUE TITLE
[Bug]:A potential goleak

### ISSUE THREAD

**Issue by user12031** [docker/libnetwork#2681] opened 2024-04-06 07:35 UTC
blocking position:
https://github.com/moby/libnetwork/blob/3797618f9a38372e8107d8c06f6ae199e1133ae8/networkdb/cluster.go#L257
The nDB.cancelCtx()  is in the func clusterLeave(), when return err ,the cancelFunc can't get executed and the goroutine leak.
https://github.com/moby/libnetwork/blob/3797618f9a38372e8107d8c06f6ae199e1133ae8/networkdb/cluster.go#L224-L243
You can reproduce the bug by making program execute the path and test it by goleak
![1712388819260](https://github.com/moby/libnetwork/assets/61485003/283fdbda-e6bb-4596-bb16-3b15b194e104)
![1712388847783](https://github.com/moby/libnetwork/assets/61485003/44bcb618-8a40-4c19-9847-2d6ded92c424)

**Comment by akerouanton** [comment] 2024-10-02 21:31
Thanks for reporting! It seems to be a duplicate of https://github.com/moby/moby/issues/47859. Since this repo is defunct, and not actively watched by maintainers, let me close this ticket.

**Closed as not planned by akerouanton** 2024-10-02 21:31 UTC
