### ISSUE TITLE
Half-open TCP connections shut down completely

### ISSUE THREAD

**Issue by gagern** [docker/libnetwork#1204] opened 2016-06-01 20:40 UTC
I wrote a service where the server waits for the client to send some data, terminate it with EOF a.k.a. `shutdown(socket, 1)`, and then the server processes said data and sends a response. So the upstream half of the TCP connection is closed far earlier than the downstream half, leaving the TCP connection in a half-open half-closed half-duplex state. Works perfectly well on localhost.

But now that I moved the server into a Docker container, things fail: the client's TCP connection closes completely as soon as the upstream half is closed. This is on Linux, with no special container configuration, using the default network setup. Here are some steps to reproduce:
1. On the host run
   
   ```
   docker run --rm -p 12345:12345 -it alpine /bin/sh
   ```
   
   For a while I had assumed alpine's musl libc as the culprit here, but since I could reproduce the issue using other linux images as well, that has been refuted.
2. Inside the container, run
   
   ```
   apk add --no-cache socat
   { sleep 10; echo Reply; } | socat -t30 - TCP-LISTEN:12345,reuseaddr
   ```
   
   This simulates a server, which listens on port 12345 and which will have its reply ready 10 seconds after the command started.
3. In a different terminal on the host, run the following command well within these 10 seconds:
   
   ```
   echo Input | socat -t30 - TCP:localhost:12345
   ```
   
   This simulates a client, sending some data to the server. It closes the sending side of the connection, then waits for up to 30 seconds for the server to send a reply and close the connection completely. However, the reply never arrives, but instead the command completes after the input has been sent, with no reply whatsoever. Wireshark will show a pair of FIN packets on the loopback device.

I don't fully understand which part of docker networking is done by the kernel, and which is done by docker, and libnetwork in particular. But as far as I understand it, the bridge device should operate at the IP layer, and not care about the inner semantics of the TCP packets it transmits. For this reason, I can't imagine the linux bridge device implementation causing this breakage. So I hope I'm reporting this in the right place. Please excuse me and correct me if not.

**Comment by EnGassa** [comment] 2017-02-15 18:01
Looks like a duplicate of
https://github.com/docker/docker/issues/27539

**Closed** 2017-09-26 18:40 UTC

**Comment by mikemorris** [comment] 2019-07-23 16:03
I'm not able to reproduce this issue on Docker for Mac version 18.09.2, build 6247962 following the steps listed - `Reply` is sent successfully after the end of the sleep and the connection is closed without any errors. Was half-close support fixed at some point, possibly by https://github.com/docker/libnetwork/pull/1598?
