### ISSUE TITLE
Mac OSX: Ethernet Bridge PDU frames are not forwarded across containers

### ISSUE THREAD

**Issue by vasu-dasari** [docker/libnetwork#2062] opened 2018-01-22 20:43 UTC
I have two containers `lldp1` and `lldp2` both running standard Ubuntu. The goal is to turn on LLDP between these two containers and perform Network discovery. I have used `lldpd` Ubuntu package to test LLDP. `lldp1:eth1` is connected to `lldp2:eth1` (share a common bridge,configured via docker-compose). I verified that normal IP connectivity between those ports is sane.

Now, I turned on lldpd on lldp1. I see that `lldp1` is sending LLDP packets on `eth1` but `lldp2` is not receiving the same. 

I tried to analyze further by sending different kinds of ethernet frames and see if they are exchanged properly. For this, I used [mausezahn](https://github.com/uweber/mausezahn) to generate various types of packets. I used following commands to do the same. (The DA Mac is the one folowing -b option)
```
mz eth1 -d 25msec -t ip -b 00:00:c2:00:00:0e -c 20
mz eth1 -d 25msec -t ip -b ff:ff:ff:ff:ff:ff -c 20
mz eth1 -d 25msec -t ip -b 01:00:c2:00:00:0e -c 20
```
All above streams sent from lldp1 are recieved properly on lldp2.

Now, I tried sending packets with LLDP DA Mac 01:81:c2:00:00:0e. These packets are not getting exchanged.
`mz eth1 -d 25msec -t ip -b 01:80:c2:00:00:0e -c 20`
Notice that DA with  01:**00**:c2:00:00:0e are exchanged properly but not DA  01:**80**:c2:00:00:0e.
This makes me believe that the bridge which is being used to connect lldp1 and lldp2 is consuming the bridge PDU packets only, and all other packets are forwarded properly.

Is there a configuration setting on preventing these PDUs from being consumed by the `internal bridge`?
Or is this a bug?
I am using "Docker for Mac", versoin `Docker version 17.12.0-ce, build c97c6d6`. On Mac I do not see docker0 interface or any bridge. So, I am not able to provide further information. I would be happy to provide more details as needed and thereby learn how to debug Docket networks on Mac as well :)

**Comment by fcrisciani** [comment] 2018-01-22 21:37
@vasu-dasari linux bridges by design drop lldp packets, I believe that here is happening the same

**Comment by vasu-dasari** [comment] 2018-01-22 21:55
Thanks @fcrisciani 

I see that we can change the Linux bridge behavior or a per bridge basis by:

`# echo 16384 > /sys/class/net/<bridge_name>/bridge/group_fwd_mask
`

1. Is there a way we can control bridge behavior using `docker <commands>`?
2. If no such option exists, on Linux hosts, I can see which bridge is being used for a container network and hence can tweak that bridge to get this done.  How can I see the same from Mac OSx based hosts?

**Comment by fcrisciani** [comment] 2018-01-22 23:11
@vasu-dasari 
1) we don't have anything specific for that 
for question number 2 let's try if @justincormack has any suggestion

**Comment by vasu-dasari** [comment] 2018-01-23 10:14
Ok. Here is to fix on Mac.

This is how my bridges look like, `docker_network_lldp_1` is the bridge that needs to forward LLDP frames.

```
$ docker network ls
NETWORK ID          NAME                      DRIVER              SCOPE
e59b848ee8b4        bridge                    bridge              local
1ce10f319e38        docker_default_lldp_net   bridge              local
56432715dc36        docker_network_lldp_1     bridge              local
e595f359303c        host                      host                local
e6f4c55b2245        none                      null                local
```

This is how we can get to the Docker VM and fix the bridge setting.

```
$ docker run -it --privileged --pid=host --rm debian nsenter -t 1 -m -u -n -i sh
/ # brctl show
bridge name bridge id       STP enabled interfaces
docker0     8000.0242578fc103   no      veth6aac176
br-1ce10f319e38     8000.024272d19cef   no      veth0a19755
                            veth7956be4
br-56432715dc36     8000.0242219661af   no      veth7ae38ef
                            veth6c38433
/ # echo 16384 > /sys/class/net/br-56432715dc36/bridge/group_fwd_mask
```
After executing above command, I started seeing LLDP frames exchanged properly.

Still, I believe it would be good to have some kind of interface to control this property(of providing a wire-like connectivity between containers, where all kinds of packets are exchanged) or make this property enabled by default.

**Comment by justincormack** [comment] 2018-01-23 11:17
The Mac is just running a Linux VM; the bridge is inside the VM which is why you can't see it on the Mac. I don't think there is a good case for specific Docker config options, you can already use an existing bridge for Docker if you want to customise its properties, rather than having Docker create it. If you want to run a heavily customised system on Docker for Mac, I would recommend you run LinuxKit https://github.com/linuxkit/linuxkit which is the upstream VM for Docker for Mac directly. It is not (yet) quite as easy to use, but it is fully customisable.

**Comment by vasu-dasari** [comment] 2018-01-23 16:25
Ok @justincormack. Thanks for the suggestion on linuxkit. Will try this later.

My use case is quite simple, I defined my topology in a docker-compose file and wanted to create and delete the containers as a whole and wanted to keep this topology separate from the existing bridges.

For people coming from VirtualBox/VMware world, where the packets go seamlessly between VMs (via Internal Network adapter) the current behavior might look puzzling.

We can close the issue if we would like to keep the behavior as is.

**Comment by fcrisciani** [comment] 2018-01-23 18:56
@vasu-dasari closing this issue at the moment, linuxkit is definitely the way to have the full control on the vm where docker is running and allows to cover more specific scenarios

**Closed by fcrisciani** 2018-01-23 18:56 UTC
