### ISSUE TITLE
Duplicate MAC address can be assigned to different running containers in the same network when using the --mac option.

### ISSUE THREAD

**Issue by djlwilder** [docker/libnetwork#1748] opened 2017-05-08 18:47 UTC
The use of the --mac option should prevent multiple running containers from being assigned the same MAC address in the same network.

**Comment by djlwilder** [comment] 2017-05-08 18:54
Here is my test script:

#!/bin/bash 
RED=$(tput setaf 1)
BLUE=$(tput setaf 4)
NORMT=$(tput sgr 0)
PASS="$BLUE Pass $NORMT"
FAIL="$RED Fail $NORMT"

echo -n "Verify the same mac cant be assigned to multiple running containers.: "
ID=`docker run --mac-address=ee:ee:ee:ee:ee:01 -id  base-net /bin/bash`
[ -z $ID ] && echo $ERROR: failed to create container. && exit 1
IP=`docker inspect --format="{{ .NetworkSettings.Networks.bridge.IPAddress }}" $ID`
MAC=`docker inspect --format="{{ .NetworkSettings.Networks.bridge.MacAddress }}" $ID`
ID2=`docker run --mac-address=ee:ee:ee:ee:ee:01 -id  base-net /bin/bash`
[ -z $ID2 ] && echo $PASS: Container creation failed as expected. && docker rm -f $ID > /dev/null && exit 0
echo $FAIL Container creation did not fail.
IP2=`docker inspect --format="{{ .NetworkSettings.Networks.bridge.IPAddress }}" $ID2`
MAC2=`docker inspect --format="{{ .NetworkSettings.Networks.bridge.MacAddress }}" $ID2`
echo Container $ID  $IP  $MAC
echo Container $ID2 $IP2 $MAC2
docker rm -f $ID $ID2 > /dev/null
`
My results:
Verify the same mac cant be assigned to multiple running containers.:  
Fail  Container creation did not fail.
Container c12b4ed3d1667c329483f578570f5934255130d1f7738016961ba1d6cea28915 
172.17.0.6 
ee:ee:ee:ee:ee:01

Container 5970f8d3cb5dfa3cc35d36ec1d6ec346d600cb197404534cb9b85dc1b21be223 
172.17.0.7 
ee:ee:ee:ee:ee:01

**Comment by fcrisciani** [comment] 2017-10-21 16:42
This is by design, the idea is that if the user decides to specify the mac address with the --mac is willing to take the ownership of the mac assignment, so the platform will leave the burden of the management to the user itself.

Closing this for now, but feel free to follow up if you have other questions

**Closed by fcrisciani** 2017-10-21 16:42 UTC
