### ISSUE TITLE
unable to disconnect a stale endpoint even with -f

### ISSUE THREAD

**Issue by paulowhyte** [docker/libnetwork#2038] opened 2017-12-15 00:20 UTC
docker --version
Docker version 17.06.0-ce, build 02c1d87

Using overlay swarm networks.

docker network inspect -v  bonuz  | grep -A 6 "consumer_consumer.2.c3ylnwvf48ym2u4ad3z91hl47"

"Name": "consumer_consumer.2.c3ylnwvf48ym2u4ad3z91hl47",
"EndpointID": "58f8b26fff072349884b87cea9858e4a1a0acac2330c6d74463930f0f3cc09e5",
"EndpointIP": "10.100.10.112",

Container consumer_consumer.2.c3ylnwvf48ym2u4ad3z91hl47  does not exists

and 

docker network disconnect -f  bonuz consumer_consumer.2.c3ylnwvf48ym2u4ad3z91hl47

does not work

**Comment by fcrisciani** [comment] 2017-12-15 17:59
@paulowhyte can you share the daemon logs? as you can imagine the information provided so far is not enough for any kind of debug...

**Comment by paulowhyte** [comment] 2017-12-16 09:34
Hi @fcrisciani .
Sorry about the incomplete information. Unfortunatly , I dont have the deamon logs anymore , however the point is : How to disconnect a endpoint when the task(container) does not exists anymore ?
I expected that the "--force" parameter was ment exactly for these scenarios .

When I tried 
docker network disconnect -f bonuz consumer_consumer.2.c3ylnwvf48ym2u4ad3z91hl47
I got
Error response from daemon: endpoint consumer_consumer.2.c3ylnwvf48ym2u4ad3z91hl47 not found

Seems like a phantom DNS entry, and, even removing the service does not remove it .
Besides that , the  IP was released and used by other service task.

I also upgraded docker to version 17.09.1-ce on the node where the container was supposed to be ( according to the network inspec ) and got the same result. 

Only disconnecting all services from the network an recreating it , we were able to fix everything. Not so good for production enviroments .

Best regards.

**Comment by fcrisciani** [comment] 2017-12-18 02:51
@paulowhyte the logs would have give a better idea of what was the state of that task and why got leaked, in 17.12 there will be several fixes for some corner cases where some tasks where potentially leaked behind if the machine where they were launched was failing.
Also 17.12 has a new network diagnostic interface that will allow to poke and remediate these conditions directly removing them from the database at run time with no need to delete the network.

**Comment by ddebroy** [comment] 2017-12-18 07:47
This issue is most likely a duplicate of https://github.com/moby/moby/issues/35548

**Comment by paulowhyte** [comment] 2017-12-18 10:24
Thanks @fcrisciani . Good to know about v17.12 improvements.

**Comment by fcrisciani** [comment] 2018-02-07 19:38
@paulowhyte were you able to reproduce on 17.12 or can we close this?

**Comment by fcrisciani** [comment] 2018-02-23 23:08
closing this, please reopen it if you still see the issue

**Closed by fcrisciani** 2018-02-23 23:08 UTC
