### ISSUE TITLE
for sandbox implementation, just network namespace?

### ISSUE THREAD

**Issue by AdoHe** [docker/libnetwork#733] opened 2015-11-03 04:21 UTC
FYI.

**Comment by pyakpyak** [comment] 2015-11-18 22:05
@AdoHe If i understand you correctly you want to be able to join any arbitrary namespace with your container? 

I agree it's very easy to apply configuration directly to net ns and then move it to a container + you're not restricted by existing api. I created a request for this ~month ago #692 . It would be nice if docker supports this directly.

**Comment by AdoHe** [comment] 2015-11-19 02:27
@pyakpyak yes, exactly what I want. I will take a look of your pr.

**Comment by mavenugo** [comment] 2015-11-19 03:18
Closing this issue as this is a dupe of https://github.com/docker/libnetwork/issues/692.

**Closed by mavenugo** 2015-11-19 03:18 UTC
