### ISSUE TITLE
Container can not join a subnet of existing subnet

### ISSUE THREAD

**Issue by takaomag** [docker/libnetwork#1650] opened 2017-02-15 06:04 UTC
## Problem
When a container belongs to a subnet X, it can not join another subnet Y (which is a **subnet of subnet X**).

## Example
```bash
$ sudo docker network create \
--driver overlay \
--subnet 10.148.0.0/15 \
--gateway 10.148.0.1 \
--ip-range 10.148.0.0/16 \
--opt "com.docker.network.driver.mtu=9001" \
xol1

$ sudo docker network create \
--driver bridge \
--subnet 10.148.0.0/14 \
--gateway 10.150.1.0 \
--ip-range 10.150.1.0/24 \
--opt "com.docker.network.bridge.name=xbr1" \
--opt "com.docker.network.bridge.enable_ip_masquerade=true" \
--opt "com.docker.network.bridge.enable_icc=true" \
--opt "com.docker.network.bridge.host_binding_ipv4=0.0.0.0" \
--opt "com.docker.network.driver.mtu=65535" \
xbr1

$ sudo docker run \
--name test-0 \
-it \
--rm \
--network xbr1 \
--ip 10.150.1.1 \
--cap-add NET_ADMIN \
--sysctl net.ipv4.ip_forward=1 \
--sysctl net.ipv4.conf.all.proxy_arp=1 \
--sysctl net.ipv4.ip_no_pmtu_disc=0 \
SOME_DOCKER_IMAGE \
/bin/bash

## On another shell
$ sudo docker network connect --ip 10.149.0.1 xol1 test-0
```

## Error message
> Error response from daemon: failed to add interface vetha6faad3 to sandbox: error setting interface "vetha6faad3" IP to 10.149.0.1/15: cannot program address 10.149.0.1/15 in sandbox interface because it conflicts with existing route {Ifindex: 1106 Dst: 10.148.0.0/14 Src: 10.150.1.1 Gw: <nil> Flags: [] Table: 254}

## The cause
https://github.com/docker/libnetwork/blob/master/osl/interface_linux.go#L462

_10.149.0.0/15_  is a subnet of _10.148.0.0/14_, not exactly same network.
I think It is neither an error nor a problem that a network node belongs to two subnets, one of which is a subnet of the other.

**Comment by aboch** [comment] 2017-02-15 06:32
Yes. This was because of docker/docker/issues/26912

**Comment by aboch** [comment] 2017-03-01 04:08
As this is the expected behavior now, I am closing this issue.

**Closed by aboch** 2017-03-01 04:08 UTC
